
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.crunii.ccn.ectchannel.server.webservice.impl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T11:07:47.686+08:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "EctChannelService",
                      portName = "EctChannelPort",
                      targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/",
                      wsdlLocation = "http://192.168.5.73:9000/intf-server/webservice/ectChannel?wsdl",
                      endpointInterface = "com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService")
                      
public class EctChannelPortImpl implements EctChannelService {

    private static final Logger LOG = Logger.getLogger(EctChannelPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfDynamicPic(java.lang.String cateId, java.lang.String channelCode)*
     */
    public DynamicPicInfo intfDynamicPic(String cateId, String channelCode) {
        LOG.info("Executing operation intfDynamicPic");
        System.out.println(cateId);
        System.out.println(channelCode);
        try {
            DynamicPicInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfGetLoginCode(java.lang.String icMacType, java.lang.String zhinengkahao, java.lang.String channelCode)*
     */
    public AppUserLoginCode intfGetLoginCode(String icMacType, String zhinengkahao, String channelCode) {
        LOG.info("Executing operation intfGetLoginCode");
        System.out.println(icMacType);
        System.out.println(zhinengkahao);
        System.out.println(channelCode);
        try {
            AppUserLoginCode _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfComboList(java.lang.String cateId, java.lang.String channelCode, java.lang.String pageNo, java.lang.String pageSize)*
     */
    public ComboListInfo intfComboList(String cateId, String channelCode, String pageNo, String pageSize) {
        LOG.info("Executing operation intfComboList");
        System.out.println(cateId);
        System.out.println(channelCode);
        System.out.println(pageNo);
        System.out.println(pageSize);
        try {
            ComboListInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfUserInfo(java.lang.String queryNo, java.lang.String queryType, java.lang.String channelCode)*
     */
    public UserInfo intfUserInfo(String queryNo, String queryType, String channelCode) {
        LOG.info("Executing operation intfUserInfo");
        System.out.println(queryNo);
        System.out.println(queryType);
        System.out.println(channelCode);
        try {
            UserInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfSendMsgCode(java.lang.String loginCode, java.lang.String channelCode)*
     */
    public ReturnData intfSendMsgCode(String loginCode, String channelCode) {
        LOG.info("Executing operation intfSendMsgCode");
        System.out.println(loginCode);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfCheckMsgRandomCode(java.lang.String accNbr, java.lang.String msgRandomCode, java.lang.String channelCode)*
     */
    public ReturnData intfCheckMsgRandomCode(String accNbr, String msgRandomCode, String channelCode) {
        LOG.info("Executing operation intfCheckMsgRandomCode");
        System.out.println(accNbr);
        System.out.println(msgRandomCode);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfAppKeyWordInfo(java.lang.String menuNumber, java.lang.String channelCode)*
     */
    public AppKeyWordInfo intfAppKeyWordInfo(String menuNumber, String channelCode) {
        LOG.info("Executing operation intfAppKeyWordInfo");
        System.out.println(menuNumber);
        System.out.println(channelCode);
        try {
            AppKeyWordInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfModifyPasswd(java.lang.String loginCode, java.lang.String oldPasswd, java.lang.String newPasswd, java.lang.String channelCode)*
     */
    public ReturnData intfModifyPasswd(String loginCode, String oldPasswd, String newPasswd, String channelCode) {
        LOG.info("Executing operation intfModifyPasswd");
        System.out.println(loginCode);
        System.out.println(oldPasswd);
        System.out.println(newPasswd);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryProductInfoList(java.lang.String qryType, java.lang.String qryId, java.lang.String channelCode)*
     */
    public AppProductInfoList intfQueryProductInfoList(String qryType, String qryId, String channelCode) {
        LOG.info("Executing operation intfQueryProductInfoList");
        System.out.println(qryType);
        System.out.println(qryId);
        System.out.println(channelCode);
        try {
            AppProductInfoList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfBalanceInfo(java.lang.String queryNo, java.lang.String queryType, java.lang.String channelCode)*
     */
    public BalanceInfo intfBalanceInfo(String queryNo, String queryType, String channelCode) {
        LOG.info("Executing operation intfBalanceInfo");
        System.out.println(queryNo);
        System.out.println(queryType);
        System.out.println(channelCode);
        try {
            BalanceInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfChangeActiveAccNbr(java.lang.String channelCode, java.lang.String custId, java.lang.String accNbr)*
     */
    public ReturnData intfChangeActiveAccNbr(String channelCode, String custId, String accNbr) {
        LOG.info("Executing operation intfChangeActiveAccNbr");
        System.out.println(channelCode);
        System.out.println(custId);
        System.out.println(accNbr);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryGuide(java.lang.String ableId, java.lang.String channelCode)*
     */
    public AppQueryGuideInfo intfQueryGuide(String ableId, String channelCode) {
        LOG.info("Executing operation intfQueryGuide");
        System.out.println(ableId);
        System.out.println(channelCode);
        try {
            AppQueryGuideInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfTVPortalImage(java.lang.String channelCode)*
     */
    public PortalInfo intfTVPortalImage(String channelCode) {
        LOG.info("Executing operation intfTVPortalImage");
        System.out.println(channelCode);
        try {
            PortalInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryGuideClassification(java.lang.String parent, java.lang.String channelCode)*
     */
    public AppQGCInfo intfQueryGuideClassification(String parent, String channelCode) {
        LOG.info("Executing operation intfQueryGuideClassification");
        System.out.println(parent);
        System.out.println(channelCode);
        try {
            AppQGCInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfBindRemove(java.lang.String custId, java.lang.String userId, java.lang.String channelCode)*
     */
    public ReturnData intfBindRemove(String custId, String userId, String channelCode) {
        LOG.info("Executing operation intfBindRemove");
        System.out.println(custId);
        System.out.println(userId);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfIntegralCreate(java.lang.String orderId, java.lang.String custId, java.lang.String bussType, java.lang.String note, java.lang.String channelCode)*
     */
    public ReturnData intfIntegralCreate(String orderId, String custId, String bussType, String note, String channelCode) {
        LOG.info("Executing operation intfIntegralCreate");
        System.out.println(orderId);
        System.out.println(custId);
        System.out.println(bussType);
        System.out.println(note);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfSendPhoneCode(java.lang.String mobilePhone, java.lang.String channelCode)*
     */
    public ReturnData intfSendPhoneCode(String mobilePhone, String channelCode) {
        LOG.info("Executing operation intfSendPhoneCode");
        System.out.println(mobilePhone);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQuerySearchResult(java.lang.String keyWord, java.lang.String condition, java.lang.String channelCode)*
     */
    public com.crunii.ccn.ectchannel.server.webservice.impl.AppSearchResultInfo intfQuerySearchResult(String keyWord, String condition, String channelCode) {
        LOG.info("Executing operation intfQuerySearchResult");
        System.out.println(keyWord);
        System.out.println(condition);
        System.out.println(channelCode);
        try {
            com.crunii.ccn.ectchannel.server.webservice.impl.AppSearchResultInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfRetrievePasswd(java.lang.String loginCode, java.lang.String phoneCode, java.lang.String passwd, java.lang.String channelCode)*
     */
    public ReturnData intfRetrievePasswd(String loginCode, String phoneCode, String passwd, String channelCode) {
        LOG.info("Executing operation intfRetrievePasswd");
        System.out.println(loginCode);
        System.out.println(phoneCode);
        System.out.println(passwd);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfCustInfo(java.lang.String queryNo, java.lang.String queryType, java.lang.String channelCode)*
     */
    public CustInfo intfCustInfo(String queryNo, String queryType, String channelCode) {
        LOG.info("Executing operation intfCustInfo");
        System.out.println(queryNo);
        System.out.println(queryType);
        System.out.println(channelCode);
        try {
            CustInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfEctServiceRel(java.lang.String serviceId, java.lang.String serviceType)*
     */
    public EctQueryComboData intfEctServiceRel(String serviceId, String serviceType) {
        LOG.info("Executing operation intfEctServiceRel");
        System.out.println(serviceId);
        System.out.println(serviceType);
        try {
            EctQueryComboData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfChangeNumber(java.lang.String userId, java.lang.String newPhone, java.lang.String newMail, java.lang.String channelCode)*
     */
    public ReturnData intfChangeNumber(String userId, String newPhone, String newMail, String channelCode) {
        LOG.info("Executing operation intfChangeNumber");
        System.out.println(userId);
        System.out.println(newPhone);
        System.out.println(newMail);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryCommonfaultList(java.lang.String channelCode)*
     */
    public AppCommonFaultList intfQueryCommonfaultList(String channelCode) {
        LOG.info("Executing operation intfQueryCommonfaultList");
        System.out.println(channelCode);
        try {
            AppCommonFaultList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfGoodsAccept(java.lang.String orderId, java.lang.String custId, java.lang.String goodsId, java.lang.String goodsAmount, java.lang.String relaNumber, java.lang.String channelCode)*
     */
    public ReturnData intfGoodsAccept(String orderId, String custId, String goodsId, String goodsAmount, String relaNumber, String channelCode) {
        LOG.info("Executing operation intfGoodsAccept");
        System.out.println(orderId);
        System.out.println(custId);
        System.out.println(goodsId);
        System.out.println(goodsAmount);
        System.out.println(relaNumber);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfPortalImage(java.lang.String channelCode)*
     */
    public PortalInfo intfPortalImage(String channelCode) {
        LOG.info("Executing operation intfPortalImage");
        System.out.println(channelCode);
        try {
            PortalInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryBusiHallInfo(java.lang.String areaId, java.lang.String type, java.lang.String channelCode)*
     */
    public AppBusiHallInfosRt intfQueryBusiHallInfo(String areaId, String type, String channelCode) {
        LOG.info("Executing operation intfQueryBusiHallInfo");
        System.out.println(areaId);
        System.out.println(type);
        System.out.println(channelCode);
        try {
            AppBusiHallInfosRt _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfUserReg(java.lang.String icMacType, java.lang.String zhinengkahao, java.lang.String nickName, java.lang.String cardType, java.lang.String kehukahao, java.lang.String loginCode, java.lang.String mobilePhone, java.lang.String phoneCode, java.lang.String passwd, java.lang.String email, java.lang.String address, java.lang.String channelCode)*
     */
    public ReturnData intfUserReg(String icMacType, String zhinengkahao, String nickName, String cardType, String kehukahao, String loginCode, String mobilePhone, String phoneCode, String passwd, String email, String address, String channelCode) {
        LOG.info("Executing operation intfUserReg");
        System.out.println(icMacType);
        System.out.println(zhinengkahao);
        System.out.println(nickName);
        System.out.println(cardType);
        System.out.println(kehukahao);
        System.out.println(loginCode);
        System.out.println(mobilePhone);
        System.out.println(phoneCode);
        System.out.println(passwd);
        System.out.println(email);
        System.out.println(address);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfNewSendMsg(java.lang.String phone, java.lang.String msgType, java.lang.String msgCategory, java.lang.String channelCode)*
     */
    public ReturnData intfNewSendMsg(String phone, String msgType, String msgCategory, String channelCode) {
        LOG.info("Executing operation intfNewSendMsg");
        System.out.println(phone);
        System.out.println(msgType);
        System.out.println(msgCategory);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryAreaInfoList(java.lang.String channelCode)*
     */
    public AppAreaInfoList intfQueryAreaInfoList(String channelCode) {
        LOG.info("Executing operation intfQueryAreaInfoList");
        System.out.println(channelCode);
        try {
            AppAreaInfoList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryVodInfo(java.lang.String servId, java.lang.String startDate, java.lang.String endDate, java.lang.String channelCode)*
     */
    public VodInfoEctChannel intfQueryVodInfo(String servId, String startDate, String endDate, String channelCode) {
        LOG.info("Executing operation intfQueryVodInfo");
        System.out.println(servId);
        System.out.println(startDate);
        System.out.println(endDate);
        System.out.println(channelCode);
        try {
            VodInfoEctChannel _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfGoodsList(java.lang.String channelCode)*
     */
    public GoodsInfo intfGoodsList(String channelCode) {
        LOG.info("Executing operation intfGoodsList");
        System.out.println(channelCode);
        try {
            GoodsInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfNewProductOrderInfo(java.lang.String prodInstId, java.lang.String channelCode)*
     */
    public com.crunii.ccn.ectchannel.server.webservice.impl.NewProductOrderInfoEct intfNewProductOrderInfo(String prodInstId, String channelCode) {
        LOG.info("Executing operation intfNewProductOrderInfo");
        System.out.println(prodInstId);
        System.out.println(channelCode);
        try {
            com.crunii.ccn.ectchannel.server.webservice.impl.NewProductOrderInfoEct _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfParentLocker(java.lang.String channelCode, java.lang.String custId, java.lang.String dealType, java.lang.String passwd, java.lang.String newPasswd)*
     */
    public ParentLocker intfParentLocker(String channelCode, String custId, String dealType, String passwd, String newPasswd) {
        LOG.info("Executing operation intfParentLocker");
        System.out.println(channelCode);
        System.out.println(custId);
        System.out.println(dealType);
        System.out.println(passwd);
        System.out.println(newPasswd);
        try {
            ParentLocker _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfComboCate(java.lang.String channelCode)*
     */
    public ComboCateInfo intfComboCate(String channelCode) {
        LOG.info("Executing operation intfComboCate");
        System.out.println(channelCode);
        try {
            ComboCateInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryBusiOrderList(java.lang.String custId, java.lang.String startTime, java.lang.String endTime, java.lang.String channelCode)*
     */
    public AppBusiOrderList intfQueryBusiOrderList(String custId, String startTime, String endTime, String channelCode) {
        LOG.info("Executing operation intfQueryBusiOrderList");
        System.out.println(custId);
        System.out.println(startTime);
        System.out.println(endTime);
        System.out.println(channelCode);
        try {
            AppBusiOrderList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfRecharge(java.lang.String soNbr, java.lang.String channelCode, java.lang.String subChannel, java.lang.String opId, java.lang.String terminalId, java.lang.String payDate, java.lang.String queryType, java.lang.String queryNo, java.util.List<com.crunii.ccn.ectchannel.server.webservice.impl.PayIn> ls)*
     */
    public com.crunii.ccn.ectchannel.server.webservice.impl.PayFeeResultExtend intfRecharge(String soNbr, String channelCode, String subChannel, String opId, String terminalId, String payDate, String queryType, String queryNo, java.util.List<PayIn> ls) {
        LOG.info("Executing operation intfRecharge");
        System.out.println(soNbr);
        System.out.println(channelCode);
        System.out.println(subChannel);
        System.out.println(opId);
        System.out.println(terminalId);
        System.out.println(payDate);
        System.out.println(queryType);
        System.out.println(queryNo);
        System.out.println(ls);
        try {
            com.crunii.ccn.ectchannel.server.webservice.impl.PayFeeResultExtend _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfOrderAppoint(java.lang.String operName, java.lang.String sex, java.lang.String dealType, java.lang.String productType, java.lang.String mobile, java.lang.String address, java.lang.String note, java.lang.String channelCode, java.lang.String comboId, java.lang.String terminalNumber, java.lang.String merchantOrderid, java.lang.String paySerialNu)*
     */
    public OrderCreateInfo intfOrderAppoint(String operName, String sex, String dealType, String productType, String mobile, String address, String note, String channelCode, String comboId, String terminalNumber, String merchantOrderid, String paySerialNu) {
        LOG.info("Executing operation intfOrderAppoint");
        System.out.println(operName);
        System.out.println(sex);
        System.out.println(dealType);
        System.out.println(productType);
        System.out.println(mobile);
        System.out.println(address);
        System.out.println(note);
        System.out.println(channelCode);
        System.out.println(comboId);
        System.out.println(terminalNumber);
        System.out.println(merchantOrderid);
        System.out.println(paySerialNu);
        try {
            OrderCreateInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryCardTypeInfo(java.lang.String typePassword, java.lang.String channelCode)*
     */
    public com.crunii.ccn.ectchannel.server.webservice.impl.QueryCardTypeResult intfQueryCardTypeInfo(String typePassword, String channelCode) {
        LOG.info("Executing operation intfQueryCardTypeInfo");
        System.out.println(typePassword);
        System.out.println(channelCode);
        try {
            com.crunii.ccn.ectchannel.server.webservice.impl.QueryCardTypeResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfModCredit(java.lang.String acctId, java.lang.String serviceId, java.lang.String credit, java.lang.String channelId)*
     */
    public ReturnData intfModCredit(String acctId, String serviceId, String credit, String channelId) {
        LOG.info("Executing operation intfModCredit");
        System.out.println(acctId);
        System.out.println(serviceId);
        System.out.println(credit);
        System.out.println(channelId);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryCustIntegral(java.lang.String custId, java.lang.String channelId, java.lang.String channelCode, java.lang.String startTime, java.lang.String endTime, java.lang.String pageNo, java.lang.String pageSize)*
     */
    public CustIntegralInfo intfQueryCustIntegral(String custId, String channelId, String channelCode, String startTime, String endTime, String pageNo, String pageSize) {
        LOG.info("Executing operation intfQueryCustIntegral");
        System.out.println(custId);
        System.out.println(channelId);
        System.out.println(channelCode);
        System.out.println(startTime);
        System.out.println(endTime);
        System.out.println(pageNo);
        System.out.println(pageSize);
        try {
            CustIntegralInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfPayCard(java.lang.String qryType, java.lang.String qryId, java.lang.String cardNum, java.lang.String cardPswd, java.lang.String channelId, java.lang.String rechargeType, java.lang.Long userId)*
     */
    public AppPayCardResult intfPayCard(String qryType, String qryId, String cardNum, String cardPswd, String channelId, String rechargeType, Long userId) {
        LOG.info("Executing operation intfPayCard");
        System.out.println(qryType);
        System.out.println(qryId);
        System.out.println(cardNum);
        System.out.println(cardPswd);
        System.out.println(channelId);
        System.out.println(rechargeType);
        System.out.println(userId);
        try {
            AppPayCardResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfOrderComplain(java.lang.String operName, java.lang.String dealType, java.lang.String theme, java.lang.String content, java.lang.String mobile, java.lang.String address, java.lang.String channelCode)*
     */
    public OrderCreateInfo intfOrderComplain(String operName, String dealType, String theme, String content, String mobile, String address, String channelCode) {
        LOG.info("Executing operation intfOrderComplain");
        System.out.println(operName);
        System.out.println(dealType);
        System.out.println(theme);
        System.out.println(content);
        System.out.println(mobile);
        System.out.println(address);
        System.out.println(channelCode);
        try {
            OrderCreateInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfComboOrder(java.lang.String servNo, java.lang.String comboId, java.lang.String channelCode, java.lang.String intfSeq, java.lang.String prePayTpye)*
     */
    public ComboOrderInfo intfComboOrder(String servNo, String comboId, String channelCode, String intfSeq, String prePayTpye) {
        LOG.info("Executing operation intfComboOrder");
        System.out.println(servNo);
        System.out.println(comboId);
        System.out.println(channelCode);
        System.out.println(intfSeq);
        System.out.println(prePayTpye);
        try {
            ComboOrderInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryPayment(java.lang.String acctId, java.lang.String corpOrgId, java.lang.String startDate, java.lang.String endDate, java.lang.String qryOnetimeFee, java.lang.String channelCode)*
     */
    public PaymentQueryInfo intfQueryPayment(String acctId, String corpOrgId, String startDate, String endDate, String qryOnetimeFee, String channelCode) {
        LOG.info("Executing operation intfQueryPayment");
        System.out.println(acctId);
        System.out.println(corpOrgId);
        System.out.println(startDate);
        System.out.println(endDate);
        System.out.println(qryOnetimeFee);
        System.out.println(channelCode);
        try {
            PaymentQueryInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfOrderQuery(java.lang.String mobile, java.lang.String startTime, java.lang.String endTime, java.lang.String channelCode)*
     */
    public AppOrderQueryInfo intfOrderQuery(String mobile, String startTime, String endTime, String channelCode) {
        LOG.info("Executing operation intfOrderQuery");
        System.out.println(mobile);
        System.out.println(startTime);
        System.out.println(endTime);
        System.out.println(channelCode);
        try {
            AppOrderQueryInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfPortalHtml(java.lang.String isCOA, java.lang.String cateOrArticleId, java.lang.String channelCode)*
     */
    public AppPortalHtmlInfo intfPortalHtml(String isCOA, String cateOrArticleId, String channelCode) {
        LOG.info("Executing operation intfPortalHtml");
        System.out.println(isCOA);
        System.out.println(cateOrArticleId);
        System.out.println(channelCode);
        try {
            AppPortalHtmlInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfNoticeInfo(java.lang.String channelCode)*
     */
    public NoticeReturnInfo intfNoticeInfo(String channelCode) {
        LOG.info("Executing operation intfNoticeInfo");
        System.out.println(channelCode);
        try {
            NoticeReturnInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfComboValid(java.lang.String servNo, java.lang.String comboId, java.lang.String channelCode)*
     */
    public ComboValidInfo intfComboValid(String servNo, String comboId, String channelCode) {
        LOG.info("Executing operation intfComboValid");
        System.out.println(servNo);
        System.out.println(comboId);
        System.out.println(channelCode);
        try {
            ComboValidInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfAcctBillInfo(java.lang.String accountId, java.lang.String month, java.lang.String ownCorpOrg, java.lang.String channelCode)*
     */
    public AcctBillInfo intfAcctBillInfo(String accountId, String month, String ownCorpOrg, String channelCode) {
        LOG.info("Executing operation intfAcctBillInfo");
        System.out.println(accountId);
        System.out.println(month);
        System.out.println(ownCorpOrg);
        System.out.println(channelCode);
        try {
            AcctBillInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfNewUserInfo(java.lang.String custId, java.lang.String channelCode)*
     */
    public NewUserInfoEct intfNewUserInfo(String custId, String channelCode) {
        LOG.info("Executing operation intfNewUserInfo");
        System.out.println(custId);
        System.out.println(channelCode);
        try {
            NewUserInfoEct _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfNewAcctInfo(java.lang.String acctId, java.lang.String corpOrgId, java.lang.String channelCode)*
     */
    public NewAcctInfoEct intfNewAcctInfo(String acctId, String corpOrgId, String channelCode) {
        LOG.info("Executing operation intfNewAcctInfo");
        System.out.println(acctId);
        System.out.println(corpOrgId);
        System.out.println(channelCode);
        try {
            NewAcctInfoEct _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfNewCustInfo(java.lang.String queryNo, java.lang.String queryType, java.lang.String channelCode)*
     */
    public NewCustInfoEct intfNewCustInfo(String queryNo, String queryType, String channelCode) {
        LOG.info("Executing operation intfNewCustInfo");
        System.out.println(queryNo);
        System.out.println(queryType);
        System.out.println(channelCode);
        try {
            NewCustInfoEct _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfBindQuery(java.lang.String userId, java.lang.String channelCode)*
     */
    public BindQueryInfo intfBindQuery(String userId, String channelCode) {
        LOG.info("Executing operation intfBindQuery");
        System.out.println(userId);
        System.out.println(channelCode);
        try {
            BindQueryInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfUserLoginInfo(java.lang.String loginType, java.lang.String loginCode, java.lang.String passWord, java.lang.String channelCode)*
     */
    public AppLoginInfo intfUserLoginInfo(String loginType, String loginCode, String passWord, String channelCode) {
        LOG.info("Executing operation intfUserLoginInfo");
        System.out.println(loginType);
        System.out.println(loginCode);
        System.out.println(passWord);
        System.out.println(channelCode);
        try {
            AppLoginInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryComplainList(java.lang.String searchNo, java.lang.String startDate, java.lang.String endDate, java.lang.String channelCode)*
     */
    public AppComplainList intfQueryComplainList(String searchNo, String startDate, String endDate, String channelCode) {
        LOG.info("Executing operation intfQueryComplainList");
        System.out.println(searchNo);
        System.out.println(startDate);
        System.out.println(endDate);
        System.out.println(channelCode);
        try {
            AppComplainList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfComboInfo(java.lang.String comboId, java.lang.String channelCode)*
     */
    public ComboInfo intfComboInfo(String comboId, String channelCode) {
        LOG.info("Executing operation intfComboInfo");
        System.out.println(comboId);
        System.out.println(channelCode);
        try {
            ComboInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfBindUserInfo(java.lang.String custName, java.lang.String cardNo, java.lang.String userId, java.lang.String qryType, java.lang.String channelCode)*
     */
    public ReturnData intfBindUserInfo(String custName, String cardNo, String userId, String qryType, String channelCode) {
        LOG.info("Executing operation intfBindUserInfo");
        System.out.println(custName);
        System.out.println(cardNo);
        System.out.println(userId);
        System.out.println(qryType);
        System.out.println(channelCode);
        try {
            ReturnData _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQuertBindMobile(java.lang.String mnAndUN, java.lang.String channelCode)*
     */
    public com.crunii.ccn.ectchannel.server.webservice.impl.BindingMobileNumber intfQuertBindMobile(String mnAndUN, String channelCode) {
        LOG.info("Executing operation intfQuertBindMobile");
        System.out.println(mnAndUN);
        System.out.println(channelCode);
        try {
            com.crunii.ccn.ectchannel.server.webservice.impl.BindingMobileNumber _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryCredit(java.lang.String acctId, java.lang.String serviceId, java.lang.String channelId)*
     */
    public CreditInfo intfQueryCredit(String acctId, String serviceId, String channelId) {
        LOG.info("Executing operation intfQueryCredit");
        System.out.println(acctId);
        System.out.println(serviceId);
        System.out.println(channelId);
        try {
            CreditInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.crunii.ccn.ectchannel.server.webservice.impl.EctChannelService#intfQueryTypeInfo(java.lang.String typeCode, java.lang.String channelCode)*
     */
    public TypeListInfo intfQueryTypeInfo(String typeCode, String channelCode) {
        LOG.info("Executing operation intfQueryTypeInfo");
        System.out.println(typeCode);
        System.out.println(channelCode);
        try {
            TypeListInfo _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
