package com.crunii.ccn.ectchannel.server.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T11:07:47.757+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", name = "EctChannelService")
@XmlSeeAlso({ObjectFactory.class})
public interface EctChannelService {

    @WebMethod
    @RequestWrapper(localName = "intfDynamicPic", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfDynamicPic")
    @ResponseWrapper(localName = "intfDynamicPicResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfDynamicPicResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DynamicPicInfo intfDynamicPic(
            @WebParam(name = "cateId", targetNamespace = "")
                    String cateId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfGetLoginCode", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfGetLoginCode")
    @ResponseWrapper(localName = "intfGetLoginCodeResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfGetLoginCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppUserLoginCode intfGetLoginCode(
            @WebParam(name = "icMacType", targetNamespace = "")
                    String icMacType,
            @WebParam(name = "zhinengkahao", targetNamespace = "")
                    String zhinengkahao,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfComboList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboList")
    @ResponseWrapper(localName = "intfComboListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ComboListInfo intfComboList(
            @WebParam(name = "cateId", targetNamespace = "")
                    String cateId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "pageNo", targetNamespace = "")
                    String pageNo,
            @WebParam(name = "pageSize", targetNamespace = "")
                    String pageSize
    );

    @WebMethod
    @RequestWrapper(localName = "intfUserInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfUserInfo")
    @ResponseWrapper(localName = "intfUserInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public UserInfo intfUserInfo(
            @WebParam(name = "queryNo", targetNamespace = "")
                    String queryNo,
            @WebParam(name = "queryType", targetNamespace = "")
                    String queryType,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfSendMsgCode", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfSendMsgCode")
    @ResponseWrapper(localName = "intfSendMsgCodeResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfSendMsgCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfSendMsgCode(
            @WebParam(name = "loginCode", targetNamespace = "")
                    String loginCode,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfCheckMsgRandomCode", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfCheckMsgRandomCode")
    @ResponseWrapper(localName = "intfCheckMsgRandomCodeResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfCheckMsgRandomCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfCheckMsgRandomCode(
            @WebParam(name = "accNbr", targetNamespace = "")
                    String accNbr,
            @WebParam(name = "msgRandomCode", targetNamespace = "")
                    String msgRandomCode,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfAppKeyWordInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfAppKeyWordInfo")
    @ResponseWrapper(localName = "intfAppKeyWordInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfAppKeyWordInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppKeyWordInfo intfAppKeyWordInfo(
            @WebParam(name = "menu_number", targetNamespace = "")
                    String menuNumber,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfModifyPasswd", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfModifyPasswd")
    @ResponseWrapper(localName = "intfModifyPasswdResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfModifyPasswdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfModifyPasswd(
            @WebParam(name = "loginCode", targetNamespace = "")
                    String loginCode,
            @WebParam(name = "oldPasswd", targetNamespace = "")
                    String oldPasswd,
            @WebParam(name = "newPasswd", targetNamespace = "")
                    String newPasswd,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryProductInfoList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryProductInfoList")
    @ResponseWrapper(localName = "intfQueryProductInfoListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryProductInfoListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.AppProductInfoList intfQueryProductInfoList(
            @WebParam(name = "qryType", targetNamespace = "")
                    String qryType,
            @WebParam(name = "qryId", targetNamespace = "")
                    String qryId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfBalanceInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBalanceInfo")
    @ResponseWrapper(localName = "intfBalanceInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBalanceInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public BalanceInfo intfBalanceInfo(
            @WebParam(name = "queryNo", targetNamespace = "")
                    String queryNo,
            @WebParam(name = "queryType", targetNamespace = "")
                    String queryType,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfChangeActiveAccNbr", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfChangeActiveAccNbr")
    @ResponseWrapper(localName = "intfChangeActiveAccNbrResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfChangeActiveAccNbrResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfChangeActiveAccNbr(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "accNbr", targetNamespace = "")
                    String accNbr
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryGuide", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryGuide")
    @ResponseWrapper(localName = "intfQueryGuideResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryGuideResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppQueryGuideInfo intfQueryGuide(
            @WebParam(name = "ableId", targetNamespace = "")
                    String ableId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfTVPortalImage", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfTVPortalImage")
    @ResponseWrapper(localName = "intfTVPortalImageResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfTVPortalImageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PortalInfo intfTVPortalImage(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryGuideClassification", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryGuideClassification")
    @ResponseWrapper(localName = "intfQueryGuideClassificationResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryGuideClassificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppQGCInfo intfQueryGuideClassification(
            @WebParam(name = "parent", targetNamespace = "")
                    String parent,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfBindRemove", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBindRemove")
    @ResponseWrapper(localName = "intfBindRemoveResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBindRemoveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfBindRemove(
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfIntegralCreate", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfIntegralCreate")
    @ResponseWrapper(localName = "intfIntegralCreateResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfIntegralCreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfIntegralCreate(
            @WebParam(name = "orderId", targetNamespace = "")
                    String orderId,
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "bussType", targetNamespace = "")
                    String bussType,
            @WebParam(name = "note", targetNamespace = "")
                    String note,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfSendPhoneCode", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfSendPhoneCode")
    @ResponseWrapper(localName = "intfSendPhoneCodeResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfSendPhoneCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfSendPhoneCode(
            @WebParam(name = "mobilePhone", targetNamespace = "")
                    String mobilePhone,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQuerySearchResult", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQuerySearchResult")
    @ResponseWrapper(localName = "intfQuerySearchResultResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQuerySearchResultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.AppSearchResultInfo intfQuerySearchResult(
            @WebParam(name = "keyWord", targetNamespace = "")
                    String keyWord,
            @WebParam(name = "condition", targetNamespace = "")
                    String condition,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfRetrievePasswd", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfRetrievePasswd")
    @ResponseWrapper(localName = "intfRetrievePasswdResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfRetrievePasswdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfRetrievePasswd(
            @WebParam(name = "loginCode", targetNamespace = "")
                    String loginCode,
            @WebParam(name = "phoneCode", targetNamespace = "")
                    String phoneCode,
            @WebParam(name = "passwd", targetNamespace = "")
                    String passwd,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfCustInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfCustInfo")
    @ResponseWrapper(localName = "intfCustInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfCustInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public CustInfo intfCustInfo(
            @WebParam(name = "queryNo", targetNamespace = "")
                    String queryNo,
            @WebParam(name = "queryType", targetNamespace = "")
                    String queryType,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfEctServiceRel", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfEctServiceRel")
    @ResponseWrapper(localName = "intfEctServiceRelResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfEctServiceRelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.EctQueryComboData intfEctServiceRel(
            @WebParam(name = "serviceId", targetNamespace = "")
                    String serviceId,
            @WebParam(name = "serviceType", targetNamespace = "")
                    String serviceType
    );

    @WebMethod
    @RequestWrapper(localName = "intfChangeNumber", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfChangeNumber")
    @ResponseWrapper(localName = "intfChangeNumberResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfChangeNumberResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfChangeNumber(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "newPhone", targetNamespace = "")
                    String newPhone,
            @WebParam(name = "newMail", targetNamespace = "")
                    String newMail,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryCommonfaultList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCommonfaultList")
    @ResponseWrapper(localName = "intfQueryCommonfaultListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCommonfaultListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.AppCommonFaultList intfQueryCommonfaultList(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfGoodsAccept", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfGoodsAccept")
    @ResponseWrapper(localName = "intfGoodsAcceptResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfGoodsAcceptResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfGoodsAccept(
            @WebParam(name = "orderId", targetNamespace = "")
                    String orderId,
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "goodsId", targetNamespace = "")
                    String goodsId,
            @WebParam(name = "goodsAmount", targetNamespace = "")
                    String goodsAmount,
            @WebParam(name = "relaNumber", targetNamespace = "")
                    String relaNumber,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfPortalImage", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfPortalImage")
    @ResponseWrapper(localName = "intfPortalImageResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfPortalImageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PortalInfo intfPortalImage(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryBusiHallInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryBusiHallInfo")
    @ResponseWrapper(localName = "intfQueryBusiHallInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryBusiHallInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.AppBusiHallInfosRt intfQueryBusiHallInfo(
            @WebParam(name = "areaId", targetNamespace = "")
                    String areaId,
            @WebParam(name = "type", targetNamespace = "")
                    String type,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfUserReg", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfUserReg")
    @ResponseWrapper(localName = "intfUserRegResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfUserRegResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfUserReg(
            @WebParam(name = "icMacType", targetNamespace = "")
                    String icMacType,
            @WebParam(name = "zhinengkahao", targetNamespace = "")
                    String zhinengkahao,
            @WebParam(name = "nickName", targetNamespace = "")
                    String nickName,
            @WebParam(name = "cardType", targetNamespace = "")
                    String cardType,
            @WebParam(name = "kehukahao", targetNamespace = "")
                    String kehukahao,
            @WebParam(name = "loginCode", targetNamespace = "")
                    String loginCode,
            @WebParam(name = "mobilePhone", targetNamespace = "")
                    String mobilePhone,
            @WebParam(name = "phoneCode", targetNamespace = "")
                    String phoneCode,
            @WebParam(name = "passwd", targetNamespace = "")
                    String passwd,
            @WebParam(name = "email", targetNamespace = "")
                    String email,
            @WebParam(name = "address", targetNamespace = "")
                    String address,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfNewSendMsg", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewSendMsg")
    @ResponseWrapper(localName = "intfNewSendMsgResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewSendMsgResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfNewSendMsg(
            @WebParam(name = "phone", targetNamespace = "")
                    String phone,
            @WebParam(name = "msgType", targetNamespace = "")
                    String msgType,
            @WebParam(name = "msgCategory", targetNamespace = "")
                    String msgCategory,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryAreaInfoList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryAreaInfoList")
    @ResponseWrapper(localName = "intfQueryAreaInfoListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryAreaInfoListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppAreaInfoList intfQueryAreaInfoList(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryVodInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryVodInfo")
    @ResponseWrapper(localName = "intfQueryVodInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryVodInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.VodInfoEctChannel intfQueryVodInfo(
            @WebParam(name = "servId", targetNamespace = "")
                    String servId,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfGoodsList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfGoodsList")
    @ResponseWrapper(localName = "intfGoodsListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfGoodsListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public GoodsInfo intfGoodsList(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfNewProductOrderInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewProductOrderInfo")
    @ResponseWrapper(localName = "intfNewProductOrderInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewProductOrderInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.NewProductOrderInfoEct intfNewProductOrderInfo(
            @WebParam(name = "prodInstId", targetNamespace = "")
                    String prodInstId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfParentLocker", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfParentLocker")
    @ResponseWrapper(localName = "intfParentLockerResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfParentLockerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ParentLocker intfParentLocker(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "dealType", targetNamespace = "")
                    String dealType,
            @WebParam(name = "passwd", targetNamespace = "")
                    String passwd,
            @WebParam(name = "newPasswd", targetNamespace = "")
                    String newPasswd
    );

    @WebMethod
    @RequestWrapper(localName = "intfComboCate", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboCate")
    @ResponseWrapper(localName = "intfComboCateResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboCateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ComboCateInfo intfComboCate(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryBusiOrderList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryBusiOrderList")
    @ResponseWrapper(localName = "intfQueryBusiOrderListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryBusiOrderListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppBusiOrderList intfQueryBusiOrderList(
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "startTime", targetNamespace = "")
                    String startTime,
            @WebParam(name = "endTime", targetNamespace = "")
                    String endTime,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfRecharge", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfRecharge")
    @ResponseWrapper(localName = "intfRechargeResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfRechargeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.PayFeeResultExtend intfRecharge(
            @WebParam(name = "SoNbr", targetNamespace = "")
                    String soNbr,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "SubChannel", targetNamespace = "")
                    String subChannel,
            @WebParam(name = "OpId", targetNamespace = "")
                    String opId,
            @WebParam(name = "TerminalId", targetNamespace = "")
                    String terminalId,
            @WebParam(name = "PayDate", targetNamespace = "")
                    String payDate,
            @WebParam(name = "queryType", targetNamespace = "")
                    String queryType,
            @WebParam(name = "queryNo", targetNamespace = "")
                    String queryNo,
            @WebParam(name = "ls", targetNamespace = "")
                    java.util.List<PayIn> ls
    );

    @WebMethod
    @RequestWrapper(localName = "intfOrderAppoint", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfOrderAppoint")
    @ResponseWrapper(localName = "intfOrderAppointResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfOrderAppointResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderCreateInfo intfOrderAppoint(
            @WebParam(name = "operName", targetNamespace = "")
                    String operName,
            @WebParam(name = "sex", targetNamespace = "")
                    String sex,
            @WebParam(name = "dealType", targetNamespace = "")
                    String dealType,
            @WebParam(name = "productType", targetNamespace = "")
                    String productType,
            @WebParam(name = "mobile", targetNamespace = "")
                    String mobile,
            @WebParam(name = "address", targetNamespace = "")
                    String address,
            @WebParam(name = "note", targetNamespace = "")
                    String note,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "comboId", targetNamespace = "")
                    String comboId,
            @WebParam(name = "terminalNumber", targetNamespace = "")
                    String terminalNumber,
            @WebParam(name = "merchantOrderid", targetNamespace = "")
                    String merchantOrderid,
            @WebParam(name = "paySerialNu", targetNamespace = "")
                    String paySerialNu
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryCardTypeInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCardTypeInfo")
    @ResponseWrapper(localName = "intfQueryCardTypeInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCardTypeInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.QueryCardTypeResult intfQueryCardTypeInfo(
            @WebParam(name = "typePassword", targetNamespace = "")
                    String typePassword,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfModCredit", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfModCredit")
    @ResponseWrapper(localName = "intfModCreditResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfModCreditResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfModCredit(
            @WebParam(name = "acctId", targetNamespace = "")
                    String acctId,
            @WebParam(name = "serviceId", targetNamespace = "")
                    String serviceId,
            @WebParam(name = "credit", targetNamespace = "")
                    String credit,
            @WebParam(name = "channelId", targetNamespace = "")
                    String channelId
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryCustIntegral", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCustIntegral")
    @ResponseWrapper(localName = "intfQueryCustIntegralResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCustIntegralResponse")
    @WebResult(name = "return", targetNamespace = "")
    public CustIntegralInfo intfQueryCustIntegral(
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "channelId", targetNamespace = "")
                    String channelId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "startTime", targetNamespace = "")
                    String startTime,
            @WebParam(name = "endTime", targetNamespace = "")
                    String endTime,
            @WebParam(name = "pageNo", targetNamespace = "")
                    String pageNo,
            @WebParam(name = "pageSize", targetNamespace = "")
                    String pageSize
    );

    @WebMethod
    @RequestWrapper(localName = "intfPayCard", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfPayCard")
    @ResponseWrapper(localName = "intfPayCardResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfPayCardResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppPayCardResult intfPayCard(
            @WebParam(name = "qryType", targetNamespace = "")
                    String qryType,
            @WebParam(name = "qryId", targetNamespace = "")
                    String qryId,
            @WebParam(name = "cardNum", targetNamespace = "")
                    String cardNum,
            @WebParam(name = "cardPswd", targetNamespace = "")
                    String cardPswd,
            @WebParam(name = "channelId", targetNamespace = "")
                    String channelId,
            @WebParam(name = "rechargeType", targetNamespace = "")
                    String rechargeType,
            @WebParam(name = "userId", targetNamespace = "")
                    Long userId
    );

    @WebMethod
    @RequestWrapper(localName = "intfOrderComplain", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfOrderComplain")
    @ResponseWrapper(localName = "intfOrderComplainResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfOrderComplainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderCreateInfo intfOrderComplain(
            @WebParam(name = "operName", targetNamespace = "")
                    String operName,
            @WebParam(name = "dealType", targetNamespace = "")
                    String dealType,
            @WebParam(name = "theme", targetNamespace = "")
                    String theme,
            @WebParam(name = "content", targetNamespace = "")
                    String content,
            @WebParam(name = "mobile", targetNamespace = "")
                    String mobile,
            @WebParam(name = "address", targetNamespace = "")
                    String address,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfComboOrder", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboOrder")
    @ResponseWrapper(localName = "intfComboOrderResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ComboOrderInfo intfComboOrder(
            @WebParam(name = "servNo", targetNamespace = "")
                    String servNo,
            @WebParam(name = "comboId", targetNamespace = "")
                    String comboId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode,
            @WebParam(name = "intfSeq", targetNamespace = "")
                    String intfSeq,
            @WebParam(name = "prePayTpye", targetNamespace = "")
                    String prePayTpye
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryPayment", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryPayment")
    @ResponseWrapper(localName = "intfQueryPaymentResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryPaymentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PaymentQueryInfo intfQueryPayment(
            @WebParam(name = "acctId", targetNamespace = "")
                    String acctId,
            @WebParam(name = "corpOrgId", targetNamespace = "")
                    String corpOrgId,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "qryOnetimeFee", targetNamespace = "")
                    String qryOnetimeFee,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfOrderQuery", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfOrderQuery")
    @ResponseWrapper(localName = "intfOrderQueryResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfOrderQueryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppOrderQueryInfo intfOrderQuery(
            @WebParam(name = "mobile", targetNamespace = "")
                    String mobile,
            @WebParam(name = "startTime", targetNamespace = "")
                    String startTime,
            @WebParam(name = "endTime", targetNamespace = "")
                    String endTime,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfPortalHtml", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfPortalHtml")
    @ResponseWrapper(localName = "intfPortalHtmlResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfPortalHtmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppPortalHtmlInfo intfPortalHtml(
            @WebParam(name = "isCOA", targetNamespace = "")
                    String isCOA,
            @WebParam(name = "cateOrArticleId", targetNamespace = "")
                    String cateOrArticleId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfNoticeInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNoticeInfo")
    @ResponseWrapper(localName = "intfNoticeInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNoticeInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NoticeReturnInfo intfNoticeInfo(
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfComboValid", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboValid")
    @ResponseWrapper(localName = "intfComboValidResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboValidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ComboValidInfo intfComboValid(
            @WebParam(name = "servNo", targetNamespace = "")
                    String servNo,
            @WebParam(name = "comboId", targetNamespace = "")
                    String comboId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfAcctBillInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfAcctBillInfo")
    @ResponseWrapper(localName = "intfAcctBillInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfAcctBillInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AcctBillInfo intfAcctBillInfo(
            @WebParam(name = "accountId", targetNamespace = "")
                    String accountId,
            @WebParam(name = "month", targetNamespace = "")
                    String month,
            @WebParam(name = "ownCorpOrg", targetNamespace = "")
                    String ownCorpOrg,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfNewUserInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewUserInfo")
    @ResponseWrapper(localName = "intfNewUserInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NewUserInfoEct intfNewUserInfo(
            @WebParam(name = "custId", targetNamespace = "")
                    String custId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfNewAcctInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewAcctInfo")
    @ResponseWrapper(localName = "intfNewAcctInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewAcctInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NewAcctInfoEct intfNewAcctInfo(
            @WebParam(name = "acctId", targetNamespace = "")
                    String acctId,
            @WebParam(name = "corpOrgId", targetNamespace = "")
                    String corpOrgId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfNewCustInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewCustInfo")
    @ResponseWrapper(localName = "intfNewCustInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfNewCustInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public NewCustInfoEct intfNewCustInfo(
            @WebParam(name = "queryNo", targetNamespace = "")
                    String queryNo,
            @WebParam(name = "queryType", targetNamespace = "")
                    String queryType,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfBindQuery", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBindQuery")
    @ResponseWrapper(localName = "intfBindQueryResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBindQueryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public BindQueryInfo intfBindQuery(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfUserLoginInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfUserLoginInfo")
    @ResponseWrapper(localName = "intfUserLoginInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfUserLoginInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppLoginInfo intfUserLoginInfo(
            @WebParam(name = "loginType", targetNamespace = "")
                    String loginType,
            @WebParam(name = "loginCode", targetNamespace = "")
                    String loginCode,
            @WebParam(name = "passWord", targetNamespace = "")
                    String passWord,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryComplainList", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryComplainList")
    @ResponseWrapper(localName = "intfQueryComplainListResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryComplainListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppComplainList intfQueryComplainList(
            @WebParam(name = "searchNo", targetNamespace = "")
                    String searchNo,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfComboInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboInfo")
    @ResponseWrapper(localName = "intfComboInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfComboInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ComboInfo intfComboInfo(
            @WebParam(name = "comboId", targetNamespace = "")
                    String comboId,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfBindUserInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBindUserInfo")
    @ResponseWrapper(localName = "intfBindUserInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfBindUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ReturnData intfBindUserInfo(
            @WebParam(name = "custName", targetNamespace = "")
                    String custName,
            @WebParam(name = "cardNo", targetNamespace = "")
                    String cardNo,
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "qryType", targetNamespace = "")
                    String qryType,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQuertBindMobile", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQuertBindMobile")
    @ResponseWrapper(localName = "intfQuertBindMobileResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQuertBindMobileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.crunii.ccn.ectchannel.server.webservice.impl.BindingMobileNumber intfQuertBindMobile(
            @WebParam(name = "MNAndUN", targetNamespace = "")
                    String mnAndUN,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryCredit", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCredit")
    @ResponseWrapper(localName = "intfQueryCreditResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryCreditResponse")
    @WebResult(name = "return", targetNamespace = "")
    public CreditInfo intfQueryCredit(
            @WebParam(name = "acctId", targetNamespace = "")
                    String acctId,
            @WebParam(name = "serviceId", targetNamespace = "")
                    String serviceId,
            @WebParam(name = "channelId", targetNamespace = "")
                    String channelId
    );

    @WebMethod
    @RequestWrapper(localName = "intfQueryTypeInfo", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryTypeInfo")
    @ResponseWrapper(localName = "intfQueryTypeInfoResponse", targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/", className = "com.crunii.ccn.ectchannel.server.webservice.impl.IntfQueryTypeInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public TypeListInfo intfQueryTypeInfo(
            @WebParam(name = "typeCode", targetNamespace = "")
                    String typeCode,
            @WebParam(name = "channelCode", targetNamespace = "")
                    String channelCode
    );
}
