package com.crunii.ccn.ectchannel.server.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T11:07:47.787+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "EctChannelService", 
                  wsdlLocation = "http://192.168.5.73:9000/intf-server/webservice/ectChannel?wsdl",
                  targetNamespace = "http://impl.webservice.server.ectchannel.ccn.crunii.com/") 
public class EctChannelService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.server.ectchannel.ccn.crunii.com/", "EctChannelService");
    public final static QName EctChannelPort = new QName("http://impl.webservice.server.ectchannel.ccn.crunii.com/", "EctChannelPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.5.73:9000/intf-server/webservice/ectChannel?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EctChannelService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.5.73:9000/intf-server/webservice/ectChannel?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EctChannelService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EctChannelService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EctChannelService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EctChannelService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EctChannelService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EctChannelService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EctChannelService
     */
    @WebEndpoint(name = "EctChannelPort")
    public EctChannelService getEctChannelPort() {
        return super.getPort(EctChannelPort, EctChannelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EctChannelService
     */
    @WebEndpoint(name = "EctChannelPort")
    public EctChannelService getEctChannelPort(WebServiceFeature... features) {
        return super.getPort(EctChannelPort, EctChannelService.class, features);
    }

}
