
package com.crunii.ccn.ectchannel.server.webservice.impl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T11:07:47.779+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class EctChannelService_EctChannelPort_Server{

    protected EctChannelService_EctChannelPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new EctChannelPortImpl();
        String address = "http://192.168.5.73:9000/intf-server/webservice/ectChannel";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new EctChannelService_EctChannelPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
